RES = 800
GRID_ROWS =80
GRID_COLS =100
CELL_SIZE = RES/GRID_ROWS
WINDOW_WIDTH = GRID_COLS * CELL_SIZE
WINDOW_HEIGHT = GRID_ROWS * CELL_SIZE

PADDING = 2
FPS = 10

NO_OF_AGENTS=200


FOOD_CAP = 50
FOOD_SPAWN_CHANCE = 0.3
MAX_ENERGY = 200
SMELL_RADIUS = 80
SURVIVAL_FACTOR=-0.08
BASE_AVAILABLE_FOODS=2
MAX_ENERGY_PER_FOOD = 400