# RES = 800
# GRID_ROWS =80
# GRID_COLS =100
# CELL_SIZE = RES/GRID_ROWS
# WINDOW_WIDTH = GRID_COLS * CELL_SIZE
# WINDOW_HEIGHT = GRID_ROWS * CELL_SIZE

# PADDING = 2
# FPS = 100

# NO_OF_AGENTS=20


# FOOD_CAP = 50
# FOOD_SPAWN_CHANCE = 0.3
# MAX_ENERGY = 400
# SMELL_RADIUS = 80
# SURVIVAL_FACTOR=-0.08
# BASE_AVAILABLE_FOODS=10
# MAX_ENERGY_PER_FOOD = 4000


# ##mating params

# WORLD_HORNINESS = 5
# HORNINESS_THRESHOLD = 0.01
# HORNINESS_WEIGHT = 0.8
# ENERGY_WEIGHT = 0.8
# DISTANCE_WEIGHT = 0.2
# MATING_COOLDOWN = 1000

######## from chatgpt ########

RES = 800
GRID_ROWS = 80
GRID_COLS = 100
CELL_SIZE = RES / GRID_ROWS
WINDOW_WIDTH = GRID_COLS * CELL_SIZE
WINDOW_HEIGHT = GRID_ROWS * CELL_SIZE

PADDING = 2
FPS = 1000

NO_OF_AGENTS = 20

# --- FOOD ---
FOOD_CAP = 35              # lower cap = tension
FOOD_SPAWN_CHANCE = 0.08   # reduced from 0.3 → prevents infinite food
MAX_ENERGY = 400
MAX_ENERGY_PER_FOOD = 1500 # reduced from 4000

SMELL_RADIUS = 25          # huge nerf so agents can't snipe food across map
SURVIVAL_FACTOR = 0.15     # makes hunger stronger than randomness
BASE_AVAILABLE_FOODS = 12
METABOLISM_RATE_GLOBAL = 2

# --- MATING ---
WORLD_HORNINESS = 0.15     # reduced MASSIVELY from 5
HORNINESS_THRESHOLD = 0.55 # increased so they don’t mate every few seconds
HORNINESS_WEIGHT = 0.6
ENERGY_WEIGHT = 1.0
DISTANCE_WEIGHT = 0.1

MATING_COOLDOWN = 1200      # big cooldown to slow population explosion
MUTATION_RATE = 0.3
MUTATION_LIMIT = 0.2