RES = 800
GRID_ROWS =80
GRID_COLS =80
CELL_SIZE = RES/GRID_ROWS
WINDOW_WIDTH = GRID_COLS * CELL_SIZE
WINDOW_HEIGHT = GRID_ROWS * CELL_SIZE

PADDING = 2
FPS = 5

NO_OF_AGENTS=100


FOOD_CAP = 20
FOOD_SPAWN_CHANCE = 1
MAX_ENERGY = 200
SMELL_RADIUS = 30